### ISSUE TITLE
Unable to include SuperAwesome SDK through Gradle

### ISSUE THREAD

**Issue by atinagrawal** [SuperAwesomeLTD/sa-mobile-sdk-android#139]
There is some problem with SuperAwesome. We have been facing this issue for months now.

This is the error I get.
Could not HEAD 'https://dl.bintray.com/gabrielcoman/maven/tv/superawesome/sdk/publisher/superawesome/8.2.4/superawesome-8.2.4.pom'. Received status code 502 from server: Bad Gateway
Disable Gradle 'offline mode' and sync project

Let me know how to integrate SDK on Android.

**Comment by atinagrawal** [comment]
Any help here?

**Comment by matheusfinatti** [comment]
@atinagrawal bintray was sunset last year. Check out the new instructions in https://sa-mobile-sdk-android.superawesome.tv/docs/add-sdk

You should be able to integrate by adding a new repository to your gradle configuration:
```gradle
repositories {
    maven { url "https://aa-sdk.s3-eu-west-1.amazonaws.com/android_repo" }
}
```

**Comment by gnhn** [comment]
Please follow the updated integration instruction from [document website](https://sa-mobile-sdk-android.superawesome.tv/docs/add-sdk).

**Comment by gnhn** [comment]
@atinagrawal Could you please check your project for the following repos and remove them?
`http://dl.bintray.com/gabrielcoman/maven`
`http://dl.bintray.com/superawesome/SuperAwesomeSDK` 

And, only include
`maven { url "https://aa-sdk.s3-eu-west-1.amazonaws.com/android_repo" }`
