### ISSUE TITLE
core-ktx:1.9.0 required minCompileSdk 33

### ISSUE THREAD

**Issue by Str4tos** [SuperAwesomeLTD/sa-mobile-sdk-android#284]
Hello. 
SuperAwesome 8.5.3 have dependency to:

https://github.com/SuperAwesomeLTD/sa-mobile-sdk-android/blob/c4d39e5cf06f5c4a2e2cde5dd033d20c2da41233/superawesome-base/build.gradle#L60

AndroidX Core version 1.9.0 required `minCompileSdk 33`, but not all frameworks currently support such an environment.  
Perhaps you could roll back the version to 1.7?

Thanks.

**Comment by me2k** [comment]
We've rolled back `androidx.core:core-ktx` from `1.9.0` to `1.7.0` in release 8.5.4

If you are not already aware, you can always exclude problem sub modules in your gradle files like so:

```
compile ("tv.superawesome.sdk.publisher:superawesome:8.5.3"){
        exclude group: 'androidx.core', module: 'core-ktx'
    } 
```
