### ISSUE TITLE
Inclusion of the MoPub Adapter Module caused replacement of the org.json library across the app

### ISSUE THREAD

**Issue by jonameson** [SuperAwesomeLTD/sa-mobile-sdk-android#37]
**What happened:**
Entire org.json library replaced and potentially obfuscated by the SuperAwesome module. This caused multiple 3rd party modules and our internal modules to fail because a different version of the org.json library was being used so it seems.

_More details about the issue posted here:_
https://stackoverflow.com/questions/65077282/why-does-minify-cause-error-jsonobjectrewards-not-a-string/65077946#65077946

**Modules Included:**
```
implementation 'tv.superawesome.sdk.publisher:superawesome:7.2.10'
implementation 'tv.superawesome.sdk.publisher:samopub:7.2.15'
implementation 'tv.superawesome.sdk.publisher:saadmob:7.2.10'
```

**Other notes:**
The issue has been fairly difficult to spot and has caused major mayhem internally and externally for our users. We've done emergency update and removed all superawesome libraries.

**Comment by gnhn** [comment]
Support to the MoPub adapter removed due to the MoPub being closed
