### ISSUE TITLE
ANR after test video ad playback completes

### ISSUE THREAD

**Issue by jonameson** [SuperAwesomeLTD/sa-mobile-sdk-android#51]
Using SDKs:

>     // Mobpub (ADS)
>     implementation('com.mopub:mopub-sdk:5.16.4@aar') {
>         transitive = true
>     }
>     // AwesomeAds (ADS)
>     implementation 'tv.superawesome.sdk.publisher:superawesome:7.2.18'
>     implementation 'tv.superawesome.sdk.publisher:samopub:7.2.18'
>     implementation 'tv.superawesome.sdk.publisher:saadmob:7.2.18'

After video playback the following message is logged multiple times fast.

> MoPub: [com.mopub.mobileads.MoPubInterstitial][onAdComplete] Ad Log - Interstitial finished.

After a little while app crashes with the following ANR.

> ActivityManager: ANR in com.vblast.flipaclip (com.vblast.flipaclip/tv.superawesome.sdk.publisher.SAVideoActivity)
>     PID: 20601
>     Reason: Input dispatching timed out (860c905 com.vblast.flipaclip/tv.superawesome.sdk.publisher.SAVideoActivity (server) is not responding. Waited 5005ms for FocusEvent(hasFocus=false))
>     Parent: com.vblast.flipaclip/tv.superawesome.sdk.publisher.SAVideoActivity
>     Load: 1.59 / 1.14 / 1.26
>     ----- Output from /proc/pressure/memory -----
>     some avg10=0.00 avg60=0.00 avg300=0.00 total=8550274
>     full avg10=0.00 avg60=0.00 avg300=0.00 total=347516
>     ----- End output from /proc/pressure/memory -----
>     
>     CPU usage from 27127ms to 0ms ago (2021-04-19 15:57:45.800 to 2021-04-19 15:58:12.927):
>       26% 20601/com.vblast.flipaclip: 22% user + 3.5% kernel / faults: 253438 minor
>       21% 1181/mediaserver: 9.9% user + 11% kernel / faults: 2371 minor
>       16% 595/surfaceflinger: 9.1% user + 6.8% kernel / faults: 29 minor
>       10% 19342/com.zhiliaoapp.musically: 9.5% user + 1.3% kernel / faults: 9770 minor 332 major
>       9.8% 1008/media.hwcodec: 3.6% user + 6.2% kernel / faults: 2581 minor
>       6.3% 1207/media.swcodec: 4.1% user + 2.1% kernel / faults: 1021 minor
>       5.1% 1625/system_server: 3.1% user + 1.9% kernel / faults: 8402 minor
>       4.7% 597/vendor.qti.hardware.display.composer-service: 2.5% user + 2.2% kernel / faults: 44 minor
>       3.8% 1045/audioserver: 2.3% user + 1.4% kernel / faults: 1 minor 1 major
>       2.5% 17750/kworker/u16:13-events_unbound: 0% user + 2.5% kernel / faults: 8 minor
>       1.6% 299/kgsl_worker_thr: 0% user + 1.6% kernel
>       1.6% 549/logd: 0.7% user + 0.9% kernel / faults: 4 minor
>       1.6% 470/crtc_commit:105: 0% user + 1.6% kernel
>       1.6% 20600/kworker/u16:5-devfreq_wq: 0% user + 1.6% kernel / faults: 3 minor
>       1.4% 17760/kworker/u16:15-ufs_pm_qos_0: 0% user + 1.4% kernel / faults: 2 minor
>       1.2% 995/rlsservice: 0.1% user + 1.1% kernel
>       1.1% 963/android.hardware.audio.service: 0% user + 1.1% kernel
>       1.1% 4316/com.android.systemui: 0.7% user + 0.3% kernel / faults: 117 minor
>       0.9% 4821/com.android.phone: 0.5% user + 0.3% kernel / faults: 417 minor
>       0.9% 19907/kworker/u16:1-memlat_wq: 0% user + 0.9% kernel / faults: 7 minor
>       0.7% 19300/com.zhiliaoapp.musically:push: 0.4% user + 0.3% kernel / faults: 641 minor 11 major
>       0.7% 11/rcu_preempt: 0% user + 0.7% kernel
>       0.6% 5294/irq/43-90b6300.: 0% user + 0.6% kernel
>       0.5% 20117/kworker/u16:4-ufs_pm_qos_0: 0% user + 0.5% kernel / faults: 1 minor
>       0.5% 5908/com.google.android.gms: 0.4% user + 0% kernel / faults: 852 minor
>       0.4% 1178/media.extractor: 0.3% user + 0.1% kernel / faults: 3 minor
>       0.4% 48/rcuop/4: 0% user + 0.4% kernel
>       0.3% 205/system: 0% user + 0.3% kernel
>       0.3% 471/crtc_event:105: 0% user + 0.3% kernel
>       0.3% 1204/qcrild: 0.2% user + 0.1% kernel / faults: 6 minor
>       0.3% 1251/adbd: 0% user + 0.2% kernel / faults: 204 minor
>       0% 9814/kworker/u16:9-memlat_wq: 0% user + 0% kernel
>       0.2% 32/rcuop/2: 0% user + 0.2% kernel
>       0.2% 3682/android.process.acore: 0.1% user + 0.1% kernel / faults: 683 minor 527 major
>       0.2% 550/lmkd: 0% user + 0.2% kernel
>       0.2% 551/servicemanager: 0.1% user + 0.1% kernel
>       0.2% 5296/irq/44-90cd000.: 0% user + 0.2% kernel
>       0.2% 10710/com.facebook.katana: 0.1% user + 0.1% kernel / faults: 6 minor 2 major
>       0.2% 32197/com.google.android.gm: 0.1% user + 0.1% kernel / faults: 151 minor 1 major
>       0.1% 1029/msm_irqbalance: 0% user + 0.1% kernel
>       0.1% 16658/com.instagram.android: 0% user + 0.1% kernel / faults: 6 minor
>       0.1% 12/rcu_sched: 0% user + 0.1% kernel
>       0.1% 949/statsd: 0.1% user + 0% kernel / faults: 30 minor
>       0.1% 10/ksoftirqd/0: 0% user + 0.1% kernel
>       0.1% 56/rcuop/5: 0% user + 0.1% kernel
>       0.1% 793/f2fs_discard-25: 0% user + 0.1% kernel
>       0.1% 950/netd: 0% user + 0% kernel / faults: 114 minor
>       0.1% 985/android.hardware.thermal@2.0-service.pixel: 0% user + 0% kernel
>       0.1% 5038/com.google.android.gms.persistent: 0% user + 0% kernel / faults: 7 minor
>       0.1% 5599/com.android.chrome: 0% user + 0% kernel / faults: 5 minor
> 2021-04-19 15:58:17.898 1625-21706/? E/ActivityManager:   0.1% 5701/com.google.android.apps.scone: 0% user + 0% kernel / faults: 11 minor
>       0.1% 7966/com.google.android.connectivitythermalpowermanager: 0% user + 0% kernel / faults: 1 minor
>       0.1% 17282/kworker/u17:1-dwc_wq: 0% user + 0.1% kernel
>       0.1% 17524/com.robinhood.android: 0.1% user + 0% kernel / faults: 82 minor
>       0% 14/rcuop/0: 0% user + 0% kernel
>       0% 15/rcuos/0: 0% user + 0% kernel
>       0% 33/rcuos/2: 0% user + 0% kernel
>       0% 40/rcuop/3: 0% user + 0% kernel
>       0% 4549/com.android.networkstack.process: 0% user + 0% kernel / faults: 69 minor 5 major
>       0% 4572/com.google.android.apps.nexuslauncher: 0% user + 0% kernel / faults: 71 minor 18 major
>       0% 16466/com.Slack: 0% user + 0% kernel / faults: 10 minor
>       0% 18074/kworker/5:3-events_power_efficient: 0% user + 0% kernel
>       0% 21454/kworker/4:2-events_power_efficient: 0% user + 0% kernel
>       0% 28241/com.twitter.android: 0% user + 0% kernel / faults: 17 minor
>       0% 31843/com.whatsapp: 0% user + 0% kernel
>       0% 21/ksoftirqd/1: 0% user + 0% kernel
>       0% 29/ksoftirqd/2: 0% user + 0% kernel
>       0% 37/ksoftirqd/3: 0% user + 0% kernel
>       0% 45/ksoftirqd/4: 0% user + 0% kernel
>       0% 49/rcuos/4: 0% user + 0% kernel
>       0% 53/ksoftirqd/5: 0% user + 0% kernel
>       0% 57/rcuos/5: 0% user + 0% kernel
>       0% 65/rcuos/6: 0% user + 0% kernel
>       0% 592/android.system.suspend@1.0-service: 0% user + 0% kernel
>       0% 983/android.hardware.sensors@2.0-service.multihal: 0% user + 0% kernel
>       0% 1513/qrtr_rx: 0% user + 0% kernel
>       0% 4329/wpa_supplicant: 0% user + 0% kernel
>       0% 4596/com.android.hbmsvmanager: 0% user + 0% kernel
>       0% 5148/com.google.android.ext.services: 0% user + 0% kernel / faults: 4 minor
>       0% 5724/com.google.android.apps.tycho:persistent: 0% user + 0% kernel
>       0% 14130/com.netgear.netgearup: 0% user + 0% kernel / faults: 4 minor
>       0% 17123/kworker/3:1-events: 0% user + 0% kernel
>       0% 19862/kworker/0:0-events: 0% user + 0% kernel
>       0% 20116/kworker/u16:3-adb: 0% user + 0% kernel
>       0% 21081/com.monday.monday: 0% user + 0% kernel
>       0% 21451/kworker/2:0-mm_percpu_wq: 0% user + 0% kernel
>      +0% 21697/logcat: 0% user + 0% kernel
>     16% TOTAL: 8.8% user + 6.6% kernel + 0% iowait + 1% irq + 0.2% softirq
>     CPU usage from 61ms to 731ms later (2021-04-19 15:58:12.988 to 2021-04-19 15:58:13.658):
>       132% 20601/com.vblast.flipaclip: 122% user + 9.9% kernel / faults: 14533 minor
>         102% 20601/blast.flipaclip: 95% user + 6.6% kernel
>         33% 20615/HeapTaskDaemon: 29% user + 3.3% kernel
>         3.3% 20617/FinalizerDaemon: 3.3% user + 0% kernel
>       68% 1625/system_server: 31% user + 37% kernel / faults: 851 minor
>         59% 21706/AnrConsumer: 23% user + 35% kernel
>         3.9% 6041/Binder:1625_16: 1.9% user + 1.9% kernel
>         1.9% 1702/android.display: 1.9% user + 0% kernel
>         1.9% 1703/android.anim: 1.9% user + 0% kernel
>         1.9% 1704/android.anim.lf: 1.9% user + 0% kernel
>       15% 595/surfaceflinger: 10% user + 5% kernel / faults: 6 minor
>         13% 595/surfaceflinger: 10% user + 3.3% kernel
>         3.3% 615/Binder:595_2: 1.6% user + 1.6% kernel
>         3.3% 686/sf: 1.6% user + 1.6% kernel
>         1.6% 683/surfaceflinger: 0% user + 1.6% kernel
>         1.6% 687/surfaceflinger: 0% user + 1.6% kernel
>       6.7% 597/vendor.qti.hardware.display.composer-service: 3.3% user + 3.3% kernel / faults: 3 minor
>         6.7% 597/Binder:597_2: 3.3% user + 3.3% kernel
>       1.5% 32/rcuop/2: 0% user + 1.5% kernel
>       1.5% 205/system: 0% user + 1.5% kernel
>       1.5% 299/kgsl_worker_thr: 0% user + 1.5% kernel
>       1.6% 470/crtc_commit:105: 0% user + 1.6% kernel
>       1.6% 549/logd: 1.6% user + 0% kernel
>         1.6% 558/logd.writer: 1.6% user + 0% kernel
>       1.7% 949/statsd: 1.7% user + 0% kernel / faults: 2 minor
>       2.2% 5294/irq/43-90b6300.: 0% user + 2.2% kernel
>       3.2% 20116/kworker/u16:3-memlat_wq: 0% user + 3.2% kernel
>     29% TOTAL: 20% user + 8.1% kernel + 0.5% irq + 0.1% softirq
> 2021-04-19 15:58:17.899 1625-21706/? D/ActivityManager: Completed ANR of com.vblast.flipaclip in 4972ms, latency 1ms

**Comment by dnharjani-sa** [comment]
Hey @jonameson

Can you try this with the latest version and see if that fixes your issues. We've updated the Mopub SDK version in order to fix some issues.

**Comment by gnhn** [comment]
MoPub adapter is removed due to MoPub has been closed.
